### PR TITLE
Release v1.1.0 preparation

### PR DESCRIPTION
**Pull request by nop33**

### CODE REVIEW

**Comment by polarker** [comment]
Can you force push again to retrigger the workflow?

**Comment by nop33** [comment]
@polarker I just did, but the problem remains... Is there something I can do to fix it?

**Comment by polarker** [comment]
Okay now. I removed the test check from branch protection.

**Review by mvaivre — APPROVED** [review]
I confirm that the build issue mentioned on Slack is gone with the new `@alephium/sdk`. Everything's working fine!

**Pull request merged**
