### PR TITLE
Optimise waves using less points and lower fps

### PR DESCRIPTION
**Pull request by LeeAlephium**
Brings the CPU usage down from ~70% peak and ~33% average to ~33% peak and ~7-10% average cpu usage

Resolves https://github.com/alephium/explorer/issues/109

### CODE REVIEW

**Comment by LeeAlephium** [comment]
I tried heavy pre-computations for the wave calculations but even this had negligible effect. The bottleneck now I believe is the GPU process... Otherwise pre-computations would've done _something_.

**Comment by LeeAlephium** [comment]
Using SVG is no better than the original way: it hits ~1/3rd of CPU usage as well, because it's probably optimizing for accuracy over performance (and thus probably also rendering per-pixel). The canvas based solution makes sense that it's faster: we're being very specific about our optimisation case.

**Comment by LeeAlephium** [comment]
After doing a series of more tests, I believe the last 10% is just GPU<->CPU call overhead that just can't be overcome. When I basically have no paint calls it still remains at around 10%. I think then this is a good benchmark to have for future animations...

**Comment by mvaivre** [comment]
Visually speaking, this looks like a good compromise to me ! 👏

**Review by mvaivre — APPROVED** [review]

**Comment by mvaivre** [comment]
@LeeAlephium While you're at it, could you port your optimisation to the website 1.5? You can just add it to my latest [PR](https://github.com/alephium/www/pull/83). Thanks!

**Review by nop33 — APPROVED** [review]
I can confirm that this optimization has reduced the CPU usage considerably.

**Pull request merged**
