### PR TITLE
Lock node and npm versions & upgrade package-lock

### PR DESCRIPTION
**Pull request by nop33**
For reference:
- https://www.npmjs.com/package/npm?activeTab=versions
- https://nodejs.org/download/release/latest-v12.x/

### CODE REVIEW

**Comment by mvaivre** [comment]
Need to find out why Github still tries to test for Node 10.x. Otherwise LGTM.

**Review by mvaivre — CHANGES_REQUESTED** [review]
Need to find out why Github still tries to test for Node 10.x. Otherwise LGTM.

**Comment by polarker** [comment]
> Need to find out why Github still tries to test for Node 10.x. Otherwise LGTM.

I removed the CI checking for Node 10.x from the settings. Now all are good

**Review by mvaivre — APPROVED** [review]

**Comment by nop33** [comment]
I can proceed with merging now, right?

**Comment by mvaivre** [comment]
> I can proceed with merging now, right?

Go ahead :)

**Pull request merged**
